# -*- coding: utf-8 -*-
"""aula04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1krh9FcKDP_leaVrAwpaZywDc5kd5bYVS
"""

# ETE PORTO DIGITAL
# PROFESSOR CLOVES ROCHA
# ESTUDANTE: MATHEUS FERNANDES SANTANA

nomes = ['Matheus', 'João', 'Leticia']
for n in nomes:
  print(n)

