# -*- coding: utf-8 -*-
"""aula03sub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ik1H1SQInoL007T0wBkw3Vhxem0a087g
"""

# ETE PORTO DIGITAL
# DISCIPLINA: LPC1
# PROFESSOR: CLOVES
# ESTUDANTE: MATHEUS F. S.

print ('Olá, ETE PORTO DIGITAL!')